version: '3'
services:
  web:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    build:
      context: ./php-fpm
    environment: 
      WAIT_FOR_HOSTS: database:3306
    env_file: .env
    depends_on:
      - database
    environment:

    volumes:
      - ../src:/var/www
  
  database:
    build:
      context: ./database
      env_file: .env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql



  

